server:
  port: 8082

spring:
  redis:
    database: 0
    password: China1234
    timeout: 10000
    sentinel:
      master: mymaster
      nodes: 172.28.13.140:26379,10.195.128.19:26379,10.195.128.20:26379
    jedis:
      pool:
        max-active: 500
        min-idle: 5
        max-idle: 50
        max-wait: 60000
