server:
  port: 8081

spring:
  redis:
    database: 0
    host: 172.28.13.140
    port: 6379
    password: China1234
    timeout: 10000
    jedis:
      pool:
        max-active: 500
        min-idle: 5
        max-idle: 50
        max-wait: 60000
